# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9a18aa3684759d80f2ce6fb0ae9ab349c8497e637c6086a90ab2899edded322ba39e07eee9f84562367dec30a9ec68dd60259ca4a6cd47bd0ce5e90dbfeea8e

test:
  secret_key_base: 61430cfc4757c2c5ef4477e195904ae241c1c90eb339bad1ef26581e06586399e2d07e368f46a08473c7d210aa14663f42ef9d7842223030f35fffaf029e4d58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
